version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "HHM-Cnvrt"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-179c0zv3mclbx"
s3_prefix = "HHM-Cnvrt"
region = "ap-northeast-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
